(define (do-request server-socket)
  (define client-socket (accept server-socket))
  (define io-stream (fdopen client-socket "r+"))
  (read-char io-stream)
  (write "HTTP/1.0 200 OK\n" io-stream)
  (write "Content-Type: text/plain\n\n" io-stream)
  (write "Hello World!\n" io-stream)
  (close io-stream)
  (do-request server-socket))

(do-request (listen "8000"))